export const productsData = [
    {
        id: 1,
        sku: 123456789123456,
        title: "Sphysx Tie Dye Grey T-Shirt",
        quantity: 1,
        sescription: "Sphysx Tie Dye Grey",
        availbaleSizes: ["X", "L", "XL", "XXL"],
        price: 10,
        isFreeShopping: true,
    },
    {
        id: 2,
        sku: 123452769823956,
        title: "Danger Knife Grey T-Shirt",
        quantity: 1,
        sescription: "Danger Knife Grey",
        availbaleSizes: ["X", "M", "L"],
        price: 14.9,
        isFreeShopping: true,
    },
    {
        id: 3,
        sku: 123466729123796,
        title: "White DGK Script Tee",
        quantity: 1,
        sescription: "White DGK Script",
        availbaleSizes: ["X", "L", "M"],
        price: 14.9,
        isFreeShopping: true,
    },
    {
        id: 4,
        sku: 123456710120452,
        title: "Born on The Streets T-Shirt",
        quantity: 1,
        sescription: "Born on The Streets",
        availbaleSizes: ["XL"],
        price: 25.9,
        isFreeShopping: true,
    },{
        id: 5,
        sku: 427456459823456,
        title: "Tso 3D Short Sleeve T-Shirt A",
        quantity: 1,
        sescription: "Tso 3D Short Sleeve",
        availbaleSizes: ["X", "L", "XL"],
        price: 10.9,
        isFreeShopping: true,
    }
    ,{
        id: 6,
        sku: 843756182223478,
        title: "Man Tie Dye Cinza Grey T-Shirt",
        quantity: 1,
        sescription: "Man Tie Dye Cinza Grey",
        availbaleSizes: ["XL", "XXL"],
        price: 29.9,
        isFreeShopping: true,
    }
]